version: 0.2
phases:
  pre_build:
    commands:
      - echo "Entered the pre-build"
  build:
    commands:
      - echo "Entered the build phase"
      - mvn clean prepare-package war:exploded
  post_build:
    commands:
      - echo "Entered the post-build phase"
artifacts:
  files:
    - target/PensionDisbursement-Microservice-0.0.1-SNAPSHOT.war